services:
  homework:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  apache-utils:
    build:
      context: .
      dockerfile: apache_utils.Dockerfile
    command: "/usr/bin/ab -k -c 10 -n 1000 http://homework:8080/index.html"
    entrypoint: ''